### ISSUE TITLE
Webpack error with exports->default in package.json

### ISSUE THREAD

**Issue by jeff-fillmore** [projectwallace/format-css#49]
First off, thanks for your work on the project!

Got this error when using webpack 5.91.0 on version 1.3.2 of format-css:
`Module not found: Error: Default condition should be last one`

Version 1.3.1 works when the last exports was default and when I manually update the package.json for format-css so the last exports is `default` then webpack works.
```
  "exports": {
    "require": "./dist/format.cjs",
    "types": "./dist/index.d.ts",
    "default": "./dist/format.modern.js"
  },
```

[Webpack documentation](https://webpack.js.org/guides/package-exports/#:~:text=The%20last%20condition%20in%20the%20object%20might%20be%20the%20special%20%22default%22%20condition%2C%20which%20is%20always%20matched.)

**Comment by bartveneman** [comment]
Thanks for reporting! Fix is in https://github.com/projectwallace/format-css/releases/tag/v1.3.3
